name:                word-frequency
version:             0.1.0.0
github:              "cbzehner/word-frequency"
license:             GPL
author:              "Chris Zehner"
maintainer:          "cbzehner@gmail.com"
copyright:           "2018 Chris Zehner"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/cbzehner/word-frequency#readme>

dependencies:
- base >= 4.7 && < 5
- directory
- filepath
- optparse-applicative
- unordered-containers

library:
  source-dirs: src

executables:
  word-frequency-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - word-frequency

tests:
  word-frequency-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - word-frequency
